import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { validWords } from '../src/Providers/validWords.ts';
import {
  compareScores,
  scoreGuess,
  twoStepScore,
  type ScoringMetric,
} from '../src/Providers/wordleMetrics.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = join(__dirname, '../src/Providers/validWords.scored.ts');

function parseRefineTop(): number {
  const flag = process.argv.find((arg) => arg.startsWith('--refine-top='));
  if (!flag) return 500;
  const value = Number(flag.split('=')[1]);
  return Number.isFinite(value) && value > 0 ? value : 500;
}

function parseSecondGuessPoolSize(): number {
  const flag = process.argv.find((arg) => arg.startsWith('--second-pool='));
  if (!flag) return 500;
  const value = Number(flag.split('=')[1]);
  return Number.isFinite(value) && value > 0 ? value : 1000;
}

function topWordsByScore(
  scores: Record<string, number>,
  metric: ScoringMetric,
  count: number,
): string[] {
  return Object.entries(scores)
    .sort(([, a], [, b]) => compareScores(a, b, metric))
    .slice(0, count)
    .map(([word]) => word);
}

function formatMap(name: string, scores: Record<string, number>): string {
  const lines = Object.entries(scores)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([word, score]) => `  "${word}": ${score},`);

  return `export const ${name}: Record<string, number> = {\n${lines.join('\n')}\n};`;
}

function scoreAllWords(words: string[], metric: ScoringMetric): Record<string, number> {
  return words.reduce((acc, word) => {
    acc[word] = scoreGuess(word, words, metric);
    return acc;
  }, {} as Record<string, number>);
}

const refineTop = parseRefineTop();
const secondGuessPoolSize = parseSecondGuessPoolSize();
console.log(`Computing 1-step scores for ${validWords.length} words...`);

const scoredExpectedRemaining = scoreAllWords(validWords, 'expectedRemaining');
const scoredEntropy = scoreAllWords(validWords, 'entropy');
const secondGuessPool = topWordsByScore(scoredEntropy, 'entropy', secondGuessPoolSize);

const refineCandidates = topWordsByScore(scoredEntropy, 'entropy', refineTop);

console.log(
  `Refining top ${refineCandidates.length} words with 2-step entropy `
  + `(second-guess pool: ${secondGuessPool.length})...`,
);

refineCandidates.forEach((word, index) => {
  if (index === 0 || (index + 1) % 25 === 0 || index + 1 === refineCandidates.length) {
    console.log(`  ${index + 1}/${refineCandidates.length}: ${word}`);
  }
  scoredEntropy[word] = twoStepScore(word, validWords, secondGuessPool, 'entropy');
});

const content = `// Generated by scripts/generate-scores.ts — do not edit manually.
${formatMap('scoredEntropy', scoredEntropy)}

${formatMap('scoredExpectedRemaining', scoredExpectedRemaining)}
`;

writeFileSync(outputPath, content);
console.log(`Wrote ${Object.keys(scoredEntropy).length} entropy scores and ${Object.keys(scoredExpectedRemaining).length} expected-remaining scores to ${outputPath}`);
