import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { validWords } from '../src/Providers/validWords.ts';
import { feedbackPattern } from '../src/Providers/wordleScore.ts';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = join(__dirname, '../src/Providers/validWords.scored.ts');

function entropyForGuess(guess: string, words: string[]): number {
  const outcomes = words.reduce((acc, word) => {
    const pattern = feedbackPattern(guess, word);
    acc[pattern] = (acc[pattern] ?? 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  return Object.values(outcomes).reduce((total, count) => {
    const prob = count / words.length;
    return total + prob * Math.log2(1 / prob);
  }, 0);
}

const scored = validWords.reduce((acc, word) => {
  acc[word] = entropyForGuess(word, validWords);
  return acc;
}, {} as Record<string, number>);

const lines = Object.entries(scored)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([word, score]) => `  "${word}": ${score},`);

const content = `// Generated by scripts/generate-scores.ts — do not edit manually.
export const scored: Record<string, number> = {
${lines.join('\n')}
};
`;

writeFileSync(outputPath, content);
console.log(`Wrote ${Object.keys(scored).length} scores to ${outputPath}`);
